about/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', aboutCoachinCenter, name='aboutCoachinCenter'),
    path('our/values/', ourvalues, name='ourvalues'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('contact_us/', include('contactUs.urls')),
    path('gallery/', include('gallery.urls')),
    path('course/', include('course.urls')),
    path('team/', include('team.urls')),
    path('about/', include('about.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

course/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('details/<slug:slug>', courseView, name='courseurl'),
    path('registration/', courseRegistration, name='registration')
]

team/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', teams, name='team')
]

about/models.py
from django.db import models


# Model for main coaching center information
class AboutCoachingCenter(models.Model):
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='coaching_center_images/')  # Directory for uploaded images
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title


# Model for additional details about the coaching center
class AboutCoachingDetails(models.Model):
    accenter = models.ForeignKey(AboutCoachingCenter, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.title


class OurValues(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title


# Model for additional details about the coaching center
class OurValuesDetails(models.Model):
    OValues = models.ForeignKey(OurValues, on_delete=models.CASCADE, related_name='details')
    title = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.title

course/models.py
from django.db import models


# Create your models here.

class Course(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title


class classSubject(models.Model):
    course_title = models.ForeignKey(Course, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class ModuleSubject(models.Model):
    course_title = models.ForeignKey(classSubject, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=255, null=True)
    description = models.TextField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class RegistrationCourse(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=11)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.first_name

index/models.py
from django.db import models
from embed_video.fields import EmbedVideoField


# Create your models here.

class Blog(models.Model):
    title = models.CharField(max_length=150)
    titleTwo = models.CharField(max_length=150)
    banar = models.ImageField(upload_to='BanarImage/')
    is_active = models.BooleanField(default=True)


class About_coching(models.Model):
    title = models.CharField(max_length=150, unique=True)
    description = models.TextField()


class Course(models.Model):
    name = models.CharField(max_length=255, unique=True)
    discription = models.TextField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Module(models.Model):
    course_title = models.ForeignKey(Course, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=255, unique=True)
    discription = models.TextField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class videos(models.Model):
    title = models.CharField(max_length=100)
    addDate = models.DateTimeField(auto_now_add=True)
    url = EmbedVideoField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return str(self.title)

    class Meta:
        ordering = ['-addDate']


class faq(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title


class faq_details(models.Model):
    faq_title = models.ForeignKey(faq, on_delete=models.CASCADE)
    question = models.CharField(max_length=255)
    answer = models.TextField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.question


class studentRegistration(models.Model):
    first_name = models.CharField(max_length=55)
    last_name = models.CharField(max_length=55)
    email = models.EmailField()
    mobile_number = models.CharField(max_length=11, unique=True)

    def __str__(self):
        return self.last_name

course/forms.py
from django import forms
from .models import RegistrationCourse


class registrationForm(forms.ModelForm):
    class Meta:
        model = RegistrationCourse
        fields = ['first_name', 'last_name', 'email', 'phone', 'course']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Customize form fields here
        self.fields['first_name'].widget.attrs.update({
            'class': 'form-control',  # Add Bootstrap class for styling
            'placeholder': 'Enter your first name'
        })
        self.fields['last_name'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Enter your last name'
        })
        self.fields['email'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Enter your email address'
        })
        self.fields['phone'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Enter your phone number'
        })
        self.fields['course'].widget.attrs.update({
            'class': 'form-control'
        })

        # Optionally, you can set labels or help texts
        self.fields['first_name'].label = 'First Name'
        self.fields['last_name'].label = 'Last Name'
        self.fields['email'].label = 'Email Address'
        self.fields['phone'].label = 'Phone Number'
        self.fields['course'].label = 'Select a Course'

about/views.py
from django.shortcuts import render
from .models import *


# Create your views here.
def aboutCoachinCenter(request):
    abouts = AboutCoachingCenter.objects.all()
    context = {
        'abouts': abouts,
    }
    return render(request, 'aboutCoachingC.html', context)


def ourvalues(request):
    values = OurValues.objects.all()
    context = {
        'values': values,
    }
    return render(request, 'our_values.html', context)

course/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *

# Create your views here.
def courseView(request, slug):
    courseDetail = Course.objects.get(slug=slug)
    classSubjects = classSubject.objects.get(course_title=courseDetail)
    ModuleSubjects = ModuleSubject.objects.filter(course_title=classSubjects)
    context = {
        'courseDetail': courseDetail,
        'classSubjects': classSubjects,
        'ModuleSubjects': ModuleSubjects,
    }
    return render(request, 'course_details.html', context)


def courseRegistration(request):
    if request.method == 'POST':
        form = registrationForm(request.POST)
        if form.is_valid():
            form.save()  # Save the registration data
            return redirect('index')  # Redirect after successful form submission
    else:
        form = registrationForm()


    return render(request, 'studen_registration.html', {'form':form})

index/templates/about.html
    <section id="about_us">
        <h2>About Us</h2>
        <div class="container">
            <div class="A-banner-0">
                <div class="row">
                    <div class="col-md-4">
                        <div class="A1-left">
                            {% for about in aboutfirstcoll %}
                            <h1>{{about.title}}</h1>
                            <p>{{ about.description}}</p>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="A1-middle">
                            {% for about in aboutseceondcoll %}
                                <h1>{{about.title}}</h1>
                                <p>{{ about.description}}</p>
                            {% endfor %}
                            <div class="A3-button">
                                <a href="#">
                                    <button class="R-button" type="button">Registration Now</button>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

index/templates/course.html
{% load static %}
<section id="course-part">
    <h2 class="text-white">Courses Offered</h2>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="carousel slide multi-item-carousel" id="theCarousel">
                    <div class="carousel-inner">
                        {% for course in courses %}
                            {% if forloop.first %}
                                <div class="item active">
                            {% else %}
                                <div class="item">
                            {% endif %}
                                <div class="col-xs-12 col-md-4">
                                    <a href="#1">
                                        <img src="{% static 'asset/image/computer.jpg' %}" class="img-responsive" alt="{{ course.name }}">
                                    </a>
                                    <p>{{ course.name }}</p>
                                    <div class="C03-button">
                                        <a href="#">
                                            <button type="button" class="see-more007">See more</button>
                                        </a>
                                    </div>
                                    <div class="C02-button">
                                        <a href="#">
                                            <button type="button" class="Course-reg07">Course registration</button>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <a class="left carousel-control" href="#theCarousel" data-slide="prev">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                    </a>
                    <a class="right carousel-control" href="#theCarousel" data-slide="next">
                        <i class="glyphicon glyphicon-chevron-right"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>

index/templates/faqs.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Faqs{% endblock %}
{% block contain %}


<body>
    <section id="title0045">
        <div class="container">
            <div class="entry-title005-left">
                <h2>Your FAQ</h2> </div>
            <ol class="breadcrumb">
                <li><a href="{% url 'index' %}">Home</a></li>
                <li><a href="#">FAQ</a></li>
            </ol>
        </div>
    </section>
    <section id="FAQgcenter002">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="faq-details357">
                    <div class="wrapper">
  <div class="half">
      {% for faq in faqs %}
    <h2>Student <strong>FAQs </strong></h2>
    <div class="tab">
        {% for i in faq.faq_details_set.all %}
        {% if i.is_active %}
      <label for="tab-one">{{ i.question }}</label>
      <div class="tab-content">
        <p>{{ i.answer }}</p>
      </div>
        {% endif %}
        {% endfor %}
    </div>
   {% endfor %}
  </div>

</div>

                    </div>

                </div>
                <div class="col-md-4">
                <div class="registration-form5y785">
                    <figure>
                    <a href="{% url 'registration' %}" class="reg-button6547">Registration Form</a>
                        <p>Book your Free Demo</p>

                    </figure>

                    </div>

                </div>
            </div>
        </div>
    </section>
    <section id="bootom-footer">
        <h4>@CopyRight By Slasstec-2017</h4> </section>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="js/jquery-3.1.1.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/isotope.pkgd.min.js"></script>
    <script src="js/isotape.function.js"></script>
    <script src="js/main.js"></script>
    <script>
        $(document).ready(function () {
            $('.reg-button6547').click(function(){
                $('.full-form0056').toggle();
            });


        });
    </script>
</body>



{% block footer %}{% endblock %}
{% endblock %}

index/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}ABC Coching{% endblock %}
{% block contain %}
<!--    Slider section -->
{% include 'slider.html' %}
<!--    about us section -->
{% include 'about.html' %}
<!--    course offered -->
{% include 'course.html' %}
<!--    your video part-->
{% include 'video.html' %}

<!--    Admission ads-->


<section id="admission-ads">
    <div class="container">
        {% for faq in faqs %}
        <div class="row">
            <div class="col-md-6">
                <div class="admission0006">
                    <h3>{{faq.title}}</h3>
                </div>
            </div>
            <div class="col-md-6">
                <div class="askqes003">
                    <a href="{% url 'faq_details' faq.slug %}" class="ques008-button">ASK QUES</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</section>

<!--    latest news part-->


<section id="latest004">
    <div class="container">
        <h2>Latest News</h2>
        <div class="row">
            <div class="col-md-3">
                <div class="coursr-01">
                    <h4>EnglishMate</h4>
                    <div class="course_02img"><img src="{% static 'asset/image/education-background-checks.jpg' %}"
                                                   alt="">
                        <h4>Why do we use it?</h4>
                        <p>It is a long established fact that a reader will be distracted by the readable content of a
                            page when looking at its layout</p>
                    </div>
                    <div class="C03-button">
                        <a href="#">
                            <button type="button" class="see-more007"> See more</button>
                        </a>
                    </div>

                </div>
            </div>
            <div class="col-md-3">
                <div class="coursr-01">
                    <h4>Economics</h4>
                    <div class="course_02img"><img src="{% static 'asset/image/education-background-checks.jpg' %}"
                                                   alt="">
                        <h4>Where does it come from?</h4>
                        <p>It is a long established fact that a reader will be distracted by the readable content of a
                            page when looking at its layout</p>
                    </div>
                    <div class="C03-button">
                        <a href="#">
                            <button type="button" class="see-more007"> See more</button>
                        </a>
                    </div>

                </div>
            </div>
            <div class="col-md-3">
                <div class="coursr-01">
                    <h4>Science</h4>
                    <div class="course_02img"><img src="{% static 'asset/image/education-background-checks.jpg' %}"
                                                   alt="">
                        <h4>Where can I get some?</h4>
                        <p>It is a long established fact that a reader will be distracted by the readable content of a
                            page when looking at its layout</p>
                    </div>
                    <div class="C03-button">
                        <a href="#">
                            <button type="button" class="see-more007"> See more</button>
                        </a>
                    </div>

                </div>
            </div>
            <div class="col-md-3">
                <div class="coursr-01">
                    <h4>Top Ranker</h4>
                    <div class="course_02img"><img src="{% static 'asset/image/education-background-checks.jpg' %}"
                                                   alt="">
                        <h4>Where can I get some?</h4>
                        <p>It is a long established fact that a reader will be distracted by the readable content of a
                            page when looking at its layout</p>
                    </div>
                    <div class="C03-button">
                        <a href="#">
                            <button type="button" class="see-more007"> See more</button>
                        </a>
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>


<!--    faculty protfolio-->

<section id="portfolio" class="text-center">
    <div class="container">
        <h2>Faculty</h2>
        <div id="filters" class="button-group">
            <button class="button is-checked" data-filter="*"><i class="fa fa-cubes" aria-hidden="true"></i></button>
            <button class="button" data-filter=".metal">Science</button>
            <button class="button" data-filter=".transition">Commerce</button>
            <button class="button" data-filter=".metal, .alkaline-earth">ARTS</button>
            <button class="button" data-filter=":not(.transition)">Other</button>
        </div>
        <div class="grid">
            <div class="element-item transition metal " data-category="transition"><img
                    src="{% static 'asset/image/tea%201.jpg' %}">
                <div class="isotope-overlay">
                    <a href="#"><h4>R Gurucharan</h4></a>
                    <h5>DEAN (STUDENT SERVICES AND PARENT ENGAGEMENT) & HOD - MATHS (XI-XII)</h5>
                    <p>Mr. Gurucharan teaches across centres for classes XI-XII. He has been responsible for helping
                        build the Mathematics department from inception. He is a...</p>
                    <div class="details005">
                        <a href="#">
                            <button class="teacher002details" type="button">See More</button>
                        </a>

                    </div>


                </div>
            </div>
            <div class="element-item metalloid " data-category="metalloid"><img
                    src="{% static 'asset/image/tea%202.jpg' %}">
                <div class="isotope-overlay">
                    <a href="#"><h4>R Gurucharan</h4></a>
                    <h5>DEAN (STUDENT SERVICES AND PARENT ENGAGEMENT) & HOD - MATHS (XI-XII)</h5>
                    <p>Mr. Gurucharan teaches across centres for classes XI-XII. He has been responsible for helping
                        build the Mathematics department from inception. He is a...</p>
                    <div class="details005">
                        <a href="#">
                            <button class="teacher002details" type="button">See More</button>
                        </a>

                    </div>
                </div>
            </div>
            <div class="element-item post-transition metal " data-category="alkaline-earth"><img
                    src="{% static 'asset/image/tea.jpg' %}">
                <div class="isotope-overlay">
                    <a href="#"><h4>R Gurucharan</h4></a>
                    <h5>DEAN (STUDENT SERVICES AND PARENT ENGAGEMENT) & HOD - MATHS (XI-XII)</h5>
                    <p>Mr. Gurucharan teaches across centres for classes XI-XII. He has been responsible for helping
                        build the Mathematics department from inception. He is a...</p>
                    <div class="details005">
                        <a href="#">
                            <button class="teacher002details" type="button">See More</button>
                        </a>

                    </div>
                </div>
            </div>


        </div>
        <div class="details003">
            <a href="#">
                <a class="teacher002details-button" href="{% url 'team' %}">See More</a>
            </a>

        </div>
    </div>
</section>

<section class="googlemap003">
    <div class="container">
        <div class="row">
            <div class="mapshow004">
                {% for p in profiles %}
                <figure>
                    <iframe src="{{ p.map_link }}"
                            width="1150" height="400" frameborder="0" style="border:0" allowfullscreen></iframe>

                </figure>
                {% endfor %}
            </div>
        </div>
    </div>


</section>
{% endblock %}

index/templates/slider.html
<section id="slider">
    <div id="first-slider">
        <div id="carousel-example-generic" class="carousel slide carousel-fade" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                {% for blog in blogs %}
                <li data-target="#carousel-example-generic" data-slide-to="{{ forloop.counter0 }}" class="{% if forloop.first %}active{% endif %}"></li>
                {% endfor %}
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
                {% for blog in blogs %}
                <div class="item {% if forloop.first %}active{% endif %}">
                    <img style="width: 100%;" src="{{ blog.banar.url }}" alt="Blog Image">
                    <div class="carousel-caption">
                        <div class="container">
                            <div class="col-md-7 text-center">
                                <h3 data-animation="animated bounceInDown">{{ blog.title }}</h3>
                                <h4 data-animation="animated bounceInUp">{{ blog.titleTwo }}</h4>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <!-- End Wrapper for slides-->

            <!-- Controls -->
            <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                <i class="fa fa-angle-left"></i>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                <i class="fa fa-angle-right"></i>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</section>

index/templates/video.html
 {% load static %}
 {% load embed_video_tags %}
    <section id="video-part">
        <h2>Concept Videos</h2>
    <div class="container">
        <div class="row">
        <div class="col-md-8">
            <div class="video-009p">
                {% for item in videos %}
                {% video item.url '754x480' %}
                {{ item.title }}
                {% endfor  %}
            </div>

            </div>

            <div class="col-md-4">
            <div class="video-info08">
                {% for video in all_videos %}
                <div class="combo007">
                <div class="thumnil001">
                    <a href="{{video.url}}">   <img src="{% static 'asset/image/7.png' %}" alt="image"></a>

                </div>
                <div class="thum002-details">
                <a href="{{video.url}}" target="_blank">{{video.title}}</a>

                </div>
                </div>
                <br>
                {% endfor %}
                </div>
            </div>
        </div>
        </div>
    </section>