about/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', aboutCoachinCenter, name='aboutCoachinCenter'),
    path('our/values/', ourvalues, name='ourvalues'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('contact_us/', include('contactUs.urls')),
    path('gallery/', include('gallery.urls')),
    path('course/', include('course.urls')),
    path('team/', include('team.urls')),
    path('about/', include('about.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

team/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', teams, name='team')
]

about/models.py
from django.db import models


# Model for main coaching center information
class AboutCoachingCenter(models.Model):
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='coaching_center_images/')  # Directory for uploaded images
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title


# Model for additional details about the coaching center
class AboutCoachingDetails(models.Model):
    accenter = models.ForeignKey(AboutCoachingCenter, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.title


class OurValues(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title


# Model for additional details about the coaching center
class OurValuesDetails(models.Model):
    OValues = models.ForeignKey(OurValues, on_delete=models.CASCADE, related_name='details')
    title = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.title

about/views.py
from django.shortcuts import render
from .models import *


# Create your views here.
def aboutCoachinCenter(request):
    abouts = AboutCoachingCenter.objects.all()
    context = {
        'abouts': abouts,
    }
    return render(request, 'aboutCoachingC.html', context)


def ourvalues(request):
    values = OurValues.objects.all()
    context = {
        'values': values,
    }
    return render(request, 'our_values.html', context)

about/templates/aboutCoachingC.html
{% extends 'base.html' %}
{% load static %}
{% block title %}About Coaching Center{% endblock %}
{% block contain %}


<section id="title0045">
    <div class="container">
        <div class="entry-title005-left">
            <h2>About Coching Center</h2></div>
        <ol class="breadcrumb">
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="#">Library</a></li>
        </ol>
    </div>
</section>
<section id="aboutcoachingcenter002">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                {% for A in abouts %}
                <div class="deatils469">
                    <figure>
                        <img src="{{ A.image.url }}" alt="{{ A.title }}">
                    </figure>
                    <div class="deatils456-info">
                        <!-- Loop through related AboutCoachingDetails objects -->
                        {% for detail in A.aboutcoachingdetails_set.all %}
                        <h3>{{ detail.title }}</h3>
                        <p>{{ detail.description }}</p> <!-- Display the description dynamically -->
                        {% endfor %}
                    </div>
                </div>
                {% endfor %}
            </div>

            <div class="col-md-4">
                <div class="registration-form5y785">
                    <figure>
                        <a href="{% url 'registration' %}" class="reg-button6547">Registration Form</a>
                        <p>Book your Free Demo</p>
                    </figure>

                </div>

            </div>
        </div>
    </div>
</section>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="js/jquery-3.1.1.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/isotope.pkgd.min.js"></script>
<script src="js/isotape.function.js"></script>
<script src="js/main.js"></script>
<script>
    $(document).ready(function () {
        $('.reg-button6547').click(function(){
            $('.full-form0056').toggle();
        });


    });
</script>


{% endblock %}

about/templates/our_values.html
{% extends 'base.html' %}
{% load static %}
{% block title %}About Coaching Center{% endblock %}
{% block contain %}

<section id="title0045">
    <div class="container">
        <div class="entry-title005-left">
            <h2>Our Values</h2></div>
        <ol class="breadcrumb">
            <li><a href="#">Home</a></li>
            <li><a href="#">Our Values</a></li>
        </ol>
    </div>
</section>
<section id="aboutcoachingcenter002">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                {% for x in values %}
                <div class="deatils469">
                    <div class="values-page5885">
                        <div class="valuedeatils356-info">
                            <p>{{ x.description }}</p>
                        </div>
                        <div class="valuedeatils356-info">
                            <!-- Loop through related AboutCoachingDetails objects -->
                            {% for detail in x.details.all %}
                            <h3>{{ detail.title }}</h3>
                            <p>{{ detail.description }}</p> <!-- Display the description dynamically -->
                            {% endfor %}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>

            <div class="col-md-4">
                <div class="registration-form5y785">
                    <figure>
                        <a href="{% url 'registration' %}" class="reg-button6547">Registration Form</a>
                        <p>Book your Free Demo</p>
                    </figure>
                </div>

            </div>
        </div>
    </div>
</section>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="js/jquery-3.1.1.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/isotope.pkgd.min.js"></script>
<script src="js/isotape.function.js"></script>
<script src="js/main.js"></script>
<script>
    $(document).ready(function () {
        $('.reg-button6547').click(function(){
            $('.full-form0056').toggle();
        });


    });
</script>

{% endblock %}